<?php
declare(strict_types=1);
require __DIR__ . '/check-ticket-simulator.php';
use Ouinpo\Suite\Modules\TicketSimulator\{TicketIntake,ScenarioValidator,ScenarioAttempt,SimulationEngine,StudentView,AttemptMarkdown};
$intakeScenario = $scenario;
$t = $intakeScenario['tickets'][0];
$t['intake_mode'] = 'from_request'; $t['raw_request'] = 'Bonjour, mon export ne marche plus depuis hier. Camille, comptabilité.';
$t['title'] = 'PRIVATE_TEACHER_TITLE'; $t['description'] = 'PRIVATE_TEACHER_DESCRIPTION';
$intakeScenario['tickets'][0] = $t;
check(ScenarioValidator::validate($intakeScenario) === $intakeScenario, 'Raw-request scenario validates');
$invalid = $intakeScenario; unset($invalid['tickets'][0]['raw_request']);
rejects(fn() => ScenarioValidator::validate($invalid), 'Raw message required in intake mode');
$state = ScenarioAttempt::initial($t);
$engine = new SimulationEngine();
rejects(fn() => $engine->perform($t, $state, 'take', []), 'Intake required before action in optional creation mode');
$a = array_merge($attempt, ['snapshot'=>json_encode($intakeScenario)]);
$view = StudentView::build($a, [$t['id']=>$state], false);
check(!str_contains(json_encode($view), 'PRIVATE_TEACHER'), 'Teacher prepared title and description are not revealed');
$form = ['title'=>'Export comptable indisponible depuis hier','requester'=>'Camille','service'=>'Comptabilité','application'=>'À confirmer','symptoms'=>'Export impossible depuis hier','missing_information'=>'Message d’erreur et périmètre','questions'=>'Quel message apparaît ? D’autres collègues sont-ils touchés ?'];
rejects(fn() => TicketIntake::save($t, $state, ['title'=>'Seul le titre']), 'Incomplete intake rejected');
[$state,$events] = TicketIntake::save($t, $state, $form);
check($events[0]['type'] === 'intake' && str_contains($events[0]['text'], $form['questions']), 'Full learner production is journalled');
[$state] = $engine->perform($t, $state, 'take', []);
check($state['status'] === 'accepted', 'Saved intake permits existing diagnostic pathway');
$form['title'] = 'Titre précisé';
[$state,$secondEvents] = TicketIntake::save($t, $state, $form);
check(str_contains($events[0]['text'], 'Export comptable') && str_contains($secondEvents[0]['text'], 'Titre précisé'), 'Earlier journal version is preserved');
$journal = [];
foreach (array_merge($events,$secondEvents) as $i=>$event) { $journal[] = ['id'=>$i+1,'ticket_key'=>$t['id'],'event_type'=>$event['type'],'created_at'=>'2026-09-16 10:00:00','payload'=>$event]; }
$md = AttemptMarkdown::render($a, [$t['id']=>$state], $journal);
check(str_contains($md, $t['raw_request']) && str_contains($md, 'Export comptable') && str_contains($md, 'Titre précisé') && str_contains($md, $form['questions']), 'Export retains original request and successive productions');
check(!str_contains($md, 'PRIVATE_TEACHER'), 'Export keeps prepared teacher text private');
rejects(fn() => TicketIntake::save($scenario['tickets'][0], $state, $form), 'Prepared mode cannot be replaced through intake route');
$closed = $state; $closed['status'] = 'closed';
rejects(fn() => TicketIntake::save($t, $closed, $form), 'Closed intake is immutable');
$current = 11; $wpdb = new FakeTicketDb(); $wpdb->attempt = $a; $wpdb->states = [['ticket_key'=>$t['id'],'state'=>json_encode(ScenarioAttempt::initial($t))]];
$route = $routes['PATCH /attempts/(?P<id>\d+)/tickets/(?P<ticket>[a-zA-Z0-9_-]+)/intake']['callback'];
$request = new WP_REST_Request(['id'=>1,'ticket'=>$t['id'],'revision'=>5] + $form);
$current = 12; check(isDenied($route($request)), 'Foreign student denied intake write');
$current = 11; check($route($request) instanceof WP_REST_Response, 'Owner can save intake through REST');
check($route($request) instanceof WP_Error, 'Stale intake revision rejected');
echo "Total: $checks checks passed including intake.\n";
