<?php
declare(strict_types=1);
require __DIR__ . '/check-ticket-advice.php';
use Ouinpo\Suite\Modules\TicketSimulator\{TicketDialogue,StudentView,ScenarioValidator,AttemptMarkdown};
use OuInPo\SegFault\OpenAI;
$current = 11; $options['ouinpo_ai_enabled'] = 1; $options['ouinpo_ai_student_per_minute'] = 100;
$config = $scenario;
$config['tickets'][0]['ai_dialogue'] = ['enabled'=>true,'requester_context'=>'REQUESTER_FACTS','specialists'=>[['specialist_id'=>'dba','context'=>'DBA_FACTS']]];
$config['tickets'][0]['expected_solution'] = 'PRIVATE_CORRECTION';
check(ScenarioValidator::validate($config) === $config, 'Dialogue configuration validates');
$invalid = $config; $invalid['tickets'][0]['ai_dialogue']['specialists'][0]['specialist_id'] = 'unknown';
rejects(fn() => ScenarioValidator::validate($invalid), 'Unknown AI specialist rejected');
$wpdb = new FakeTicketDb(); $wpdb->attempt = array_merge($attempt, ['snapshot'=>json_encode($config), 'revision'=>1]);
$wpdb->states = [['ticket_key'=>'INC-0001','state'=>json_encode($initial)]];
$view = StudentView::build($wpdb->attempt, ['INC-0001'=>$initial], false);
check(count($view['tickets'][0]['ai_recipients']) === 2 && !str_contains(json_encode($view), 'DBA_FACTS'), 'Student sees recipient labels but not role sheets');
$route = $routes['POST /attempts/(?P<id>\d+)/tickets/(?P<ticket>[a-zA-Z0-9_-]+)/dialogue']['callback'];
$req = new WP_REST_Request(['id'=>1,'ticket'=>'INC-0001','revision'=>1,'recipient'=>'requester','message'=>'Depuis quand ?']);
$calls = OpenAI::$calls; $current = 12;
check(isDenied($route($req)) && OpenAI::$calls === $calls, 'Foreign user denied before provider call');
$current = 11; OpenAI::$answer = '{"reply":"Depuis hier."}';
check($route($req) instanceof WP_REST_Response, 'Requester conversation saved');
$sent = json_encode(OpenAI::$messages);
check(str_contains($sent, 'REQUESTER_FACTS') && !str_contains($sent, 'DBA_FACTS') && !str_contains($sent, 'PRIVATE_CORRECTION'), 'Requester gets only authorized facts');
$state = json_decode($wpdb->states[0]['state'], true);
check($state['done'] === [] && $state['status'] === 'new' && $state['tests'] === [], 'Conversation cannot complete actions or tests');
$req = new WP_REST_Request(['id'=>1,'ticket'=>'INC-0001','revision'=>2,'recipient'=>'specialist:dba','message'=>'La migration a-t-elle eu lieu ?']);
check($route($req) instanceof WP_REST_Response, 'Specialist conversation saved');
$sent = json_encode(OpenAI::$messages);
check(str_contains($sent, 'DBA_FACTS') && !str_contains($sent, 'REQUESTER_FACTS') && !str_contains($sent, 'Depuis quand'), 'Specialist does not receive requester facts or history');
$before = $wpdb->states;
OpenAI::$answer = 'Provider error';
$req = new WP_REST_Request(['id'=>1,'ticket'=>'INC-0001','revision'=>3,'recipient'=>'requester','message'=>'Quel message voyez-vous ?']);
check($route($req) instanceof WP_Error && $wpdb->states === $before && (int)$wpdb->attempt['revision'] === 3, 'Provider failure leaves no partial exchange');
$calls = OpenAI::$calls;
$options['ouinpo_ai_enabled'] = 0;
check($route($req) instanceof WP_Error && OpenAI::$calls === $calls, 'Global AI switch enforced');
$options['ouinpo_ai_enabled'] = 1;
$options['ouinpo_ai_student_per_minute'] = 1;
check($route($req) instanceof WP_Error && OpenAI::$calls === $calls, 'Dialogue quota enforced');
$options['ouinpo_ai_student_per_minute'] = 100;
$req = new WP_REST_Request(['id'=>1,'ticket'=>'INC-0001','revision'=>3,'recipient'=>'specialist:unknown','message'=>'Bonjour']);
check($route($req) instanceof WP_Error && OpenAI::$calls === $calls, 'Unconfigured specialist cannot be contacted');
$journal = [['id'=>1,'ticket_key'=>'INC-0001','event_type'=>'ai_question','created_at'=>'2026-09-16 10:00:00','payload'=>['text'=>'Question libre enregistrée']],['id'=>2,'ticket_key'=>'INC-0001','event_type'=>'ai_reply','created_at'=>'2026-09-16 10:00:01','payload'=>['text'=>'Réponse IA enregistrée']]];
$md = AttemptMarkdown::render($wpdb->attempt, ['INC-0001'=>$state], $journal);
check(str_contains($md, 'Question libre enregistrée') && str_contains($md, 'Réponse IA enregistrée') && !str_contains($md, 'DBA_FACTS'), 'Export includes exchanges but hides role sheets');
echo "Total: $checks checks passed including AI dialogue.\n";
