<?php
declare(strict_types=1);
require __DIR__.'/check-ticket-simulator.php';
use Ouinpo\Suite\Modules\TicketSimulator\{AttemptDrafts,AttemptRepository,ScenarioAttempt,Assessment,AttemptMarkdown};

$current=11;
$trackingDisabled=false;
$scenario=require dirname(__DIR__).'/src/Modules/TicketSimulator/demo.php';
$ticket=$scenario['tickets'][0]['id'];
$wpdb=new FakeTicketDb();
$wpdb->attempt=['id'=>1,'student_id'=>11,'teacher_id'=>20,'snapshot'=>json_encode($scenario),'status'=>'active','revision'=>0,'ended_at'=>null];
$wpdb->states=[['ticket_key'=>$ticket,'state'=>json_encode(ScenarioAttempt::initial($scenario['tickets'][0]))]];
$key=$ticket.':notes:message';
$code=$ticket.':code:code';
$d=AttemptDrafts::save(1,['revision'=>0,'values'=>[$key=>'Note privée',$code=>'<?php echo "test"; ?>']]);
check($d['revision']===1 && $wpdb->attempt['revision']===0,'Draft saving does not change simulation revision');
check(AttemptDrafts::data((new AttemptRepository())->get(1))['values'][$code]==='<?php echo "test"; ?>','Code round trips verbatim');
rejects(fn()=>AttemptDrafts::save(1,['revision'=>0,'values'=>[]]),'Stale window cannot overwrite drafts');
$before=$wpdb->attempt;
foreach([12,20,1] as $current) { rejects(fn()=>AttemptDrafts::save(1,['revision'=>1,'values'=>[]]),'Non-owner cannot write drafts'); }
$current=20;
$view=$routes['GET /attempts/(?P<id>\d+)']['callback'](new WP_REST_Request(['id'=>1]));
check(!isset($view->data['drafts']),'Teacher observation never exposes private scratch work');
$current=11;
$view=$routes['GET /attempts/(?P<id>\d+)']['callback'](new WP_REST_Request(['id'=>1]));
check($view->data['drafts']['values'][$key]==='Note privée','Owner retrieves server drafts after reload');
$trackingDisabled=true;
rejects(fn()=>AttemptDrafts::save(1,['revision'=>1,'values'=>[]]),'Disabled learning tracking blocks draft storage');
$trackingDisabled=false;
rejects(fn()=>AttemptDrafts::save(1,['revision'=>1,'values'=>['foreign:notes:message'=>'x']]),'Unknown ticket rejected');
rejects(fn()=>AttemptDrafts::save(1,['revision'=>1,'values'=>[$key=>str_repeat('x',10001)]]),'Oversized text rejected');
check($wpdb->attempt===$before,'Denied writes leave drafts unchanged');
$wpdb->failEvents=true;
rejects(fn()=>(new AttemptRepository())->mutate(1,$ticket,0,'note',['message'=>'Note privée']),'Failed work validation rolls back');
check(AttemptDrafts::data($wpdb->attempt)['values'][$key]==='Note privée','Failed validation retains draft');
$wpdb->failEvents=false;
(new AttemptRepository())->mutate(1,$ticket,0,'note',['message'=>'Note privée']);
$d=AttemptDrafts::data($wpdb->attempt);
check(!isset($d['values'][$key]) && isset($d['values'][$code]),'Validation consumes only the submitted field, preserving code');
check($d['revision']===2,'Consumption advances the draft revision atomically');
$settings=Assessment::validate(['mode'=>'graded','rubric'=>array_values(Assessment::templates())[0]],$scenario);
$wpdb->attempt['assessment']=json_encode(['settings'=>$settings,'state'=>'working','submissions'=>[],'history'=>[]]);
rejects(fn()=>Assessment::change(1,'submit',['revision'=>1,'confirm'=>true]),'Server refuses submission with unvalidated drafts');
AttemptDrafts::save(1,['revision'=>2,'values'=>[]]);
check(AttemptDrafts::data($wpdb->attempt)['values']===[],'Explicit discard clears drafts');
$wpdb->attempt['assessment']=json_encode(['settings'=>$settings,'state'=>'submitted']);
rejects(fn()=>AttemptDrafts::save(1,['revision'=>3,'values'=>[$key=>'late']]),'Submitted assessment cannot receive new drafts');
$wpdb->attempt['status']='archived';
rejects(fn()=>AttemptDrafts::save(1,['revision'=>3,'values'=>[$key=>'late']]),'Archived attempt cannot receive new drafts');
echo "Server drafts: owner isolation, reload, optimistic locking, validation, submission and rollback passed.\n";
